# Değişken Standardizasyonu(Veri Standardizasyonu)

In [2]:
import numpy as np
import pandas as pd

In [3]:
V1= np.array([1,3,6,5,7])
V2= np.array([7,7,5,8,12])
V3= np.array([6,12,5,6,14])
df = pd.DataFrame(
     {'V1': V1,
      'V2': V2,
      'V3': V3})


In [4]:
df =df.astype(float)

In [5]:
df

V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

### Standardizasyon

In [1]:
from sklearn import preprocessing

In [6]:
preprocessing.scale(df)

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

In [7]:
df.mean()

V1    4.4
V2    7.8
V3    8.6
dtype: float64

### Normalizasyon

In [8]:
preprocessing.normalize(df)

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

### Min-Max Dönüşümü

In [13]:
scaler = preprocessing.MinMaxScaler(feature_range= (25,200))

In [14]:
scaler.fit_transform(df)

array([[ 25.        ,  75.        ,  44.44444444],
       [ 83.33333333,  75.        , 161.11111111],
       [170.83333333,  25.        ,  25.        ],
       [141.66666667, 100.        ,  44.44444444],
       [200.        , 200.        , 200.        ]])

## Değişken Dönüşümleri
* not Değişken dönüşümleri > Standardizasyon , yani her bir Standardizasyon bir değişken dönüşümüdür zaten ! 

In [41]:
import seaborn as sns
df= sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

#### 0-1 Dönüşümü

In [42]:
from sklearn.preprocessing import LabelEncoder

In [43]:
lbe= LabelEncoder()

In [44]:
lbe.fit_transform(df.sex)

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [45]:
df['new_sex'] = lbe.fit_transform(df.sex)

In [46]:
df

total_bill   tip     sex smoker   day    time  size  new_sex
0         16.99  1.01  Female     No   Sun  Dinner     2        0
1         10.34  1.66    Male     No   Sun  Dinner     3        1
2         21.01  3.50    Male     No   Sun  Dinner     3        1
3         23.68  3.31    Male     No   Sun  Dinner     2        1
4         24.59  3.61  Female     No   Sun  Dinner     4        0
..          ...   ...     ...    ...   ...     ...   ...      ...
239       29.03  5.92    Male     No   Sat  Dinner     3        1
240       27.18  2.00  Female    Yes   Sat  Dinner     2        0
241       22.67  2.00    Male    Yes   Sat  Dinner     2        1
242       17.82  1.75    Male     No   Sat  Dinner     2        1
243       18.78  3.00  Female     No  Thur  Dinner     2        0

[244 rows x 8 columns]

### "1 ve Diğerleri(0)" dönüşümü

In [47]:
df.head()

total_bill   tip     sex smoker  day    time  size  new_sex
0       16.99  1.01  Female     No  Sun  Dinner     2        0
1       10.34  1.66    Male     No  Sun  Dinner     3        1
2       21.01  3.50    Male     No  Sun  Dinner     3        1
3       23.68  3.31    Male     No  Sun  Dinner     2        1
4       24.59  3.61  Female     No  Sun  Dinner     4        0

In [55]:
df['new_day'] = np.where(df.day.str.contains('Sun'), 1 , 0)

In [56]:
df

total_bill   tip     sex smoker   day    time  size  new_sex  new_day
0         16.99  1.01  Female     No   Sun  Dinner     2        0        1
1         10.34  1.66    Male     No   Sun  Dinner     3        1        1
2         21.01  3.50    Male     No   Sun  Dinner     3        1        1
3         23.68  3.31    Male     No   Sun  Dinner     2        1        1
4         24.59  3.61  Female     No   Sun  Dinner     4        0        1
..          ...   ...     ...    ...   ...     ...   ...      ...      ...
239       29.03  5.92    Male     No   Sat  Dinner     3        1        0
240       27.18  2.00  Female    Yes   Sat  Dinner     2        0        0
241       22.67  2.00    Male    Yes   Sat  Dinner     2        1        0
242       17.82  1.75    Male     No   Sat  Dinner     2        1        0
243       18.78  3.00  Female     No  Thur  Dinner     2        0        0

[244 rows x 9 columns]

### Çok sınıflı Dönüşüm

In [27]:
from sklearn.preprocessing import LabelEncoder
lbe= LabelEncoder()

In [28]:
lbe.fit_transform(df.day)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

##### çok dikkat ! 
* kategorik değişkeni nümerik bir formata çevirdiğimizde, algoritmaların kafası karışır. Kategorik değişkenin sınıflarının bağımlı değişkene olan etkileri bozulacaktır ! bu durumun önüne geçmek için onehotencoding kullanacağız ! 

# One Hot Dönüşümü ve Dummy Değişken Tuzağı

In [29]:
df.head()

total_bill   tip     sex smoker  day    time  size  new_sex  new_day
0       16.99  1.01  Female     No  Sun  Dinner     2        0        1
1       10.34  1.66    Male     No  Sun  Dinner     3        1        1
2       21.01  3.50    Male     No  Sun  Dinner     3        1        1
3       23.68  3.31    Male     No  Sun  Dinner     2        1        1
4       24.59  3.61  Female     No  Sun  Dinner     4        0        1

In [35]:
df_one_hot = pd.get_dummies(df, columns= ['sex'], prefix= ['sex'] )

In [36]:
df_one_hot

total_bill   tip smoker   day    time  size  new_sex  new_day  sex_Male  \
0         16.99  1.01     No   Sun  Dinner     2        0        1         0   
1         10.34  1.66     No   Sun  Dinner     3        1        1         1   
2         21.01  3.50     No   Sun  Dinner     3        1        1         1   
3         23.68  3.31     No   Sun  Dinner     2        1        1         1   
4         24.59  3.61     No   Sun  Dinner     4        0        1         0   
..          ...   ...    ...   ...     ...   ...      ...      ...       ...   
239       29.03  5.92     No   Sat  Dinner     3        1        1         1   
240       27.18  2.00    Yes   Sat  Dinner     2        0        1         0   
241       22.67  2.00    Yes   Sat  Dinner     2        1        1         1   
242       17.82  1.75     No   Sat  Dinner     2        1        1         1   
243       18.78  3.00     No  Thur  Dinner     2        0        1         0   

     sex_Female  
0             1  
1             0  
2             0  
3             0  
4             1  
..          ...  
239           0  
240           1  
241           0  
242           0  
243           1  

[244 rows x 10 columns]

In [40]:
 pd.get_dummies(df, columns= ['day'], prefix= ['day'])

total_bill   tip     sex smoker    time  size  new_sex  new_day  \
0         16.99  1.01  Female     No  Dinner     2        0        1   
1         10.34  1.66    Male     No  Dinner     3        1        1   
2         21.01  3.50    Male     No  Dinner     3        1        1   
3         23.68  3.31    Male     No  Dinner     2        1        1   
4         24.59  3.61  Female     No  Dinner     4        0        1   
..          ...   ...     ...    ...     ...   ...      ...      ...   
239       29.03  5.92    Male     No  Dinner     3        1        1   
240       27.18  2.00  Female    Yes  Dinner     2        0        1   
241       22.67  2.00    Male    Yes  Dinner     2        1        1   
242       17.82  1.75    Male     No  Dinner     2        1        1   
243       18.78  3.00  Female     No  Dinner     2        0        1   

     day_Thur  day_Fri  day_Sat  day_Sun  
0           0        0        0        1  
1           0        0        0        1  
2           0        0        0        1  
3           0        0        0        1  
4           0        0        0        1  
..        ...      ...      ...      ...  
239         0        0        1        0  
240         0        0        1        0  
241         0        0        1        0  
242         0        0        1        0  
243         1        0        0        0  

[244 rows x 12 columns]

# Bölüm Sonu değerlendirmesi
* Veri Ön işleme
* Aykırı Gözlem analizi
* Eksik Gözlem Analizi
* Değişken Standartlaştırma
* Değişken Dönüştürme