In [1]:
print('numpy')

numpy


Numerical Python

Bilimsel Hesaplamalar için kullanılır

Arrayler / çk boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.

Temelleri 1995'te (matrix-sig,Guido Van Rossum) atılmış nihai olarak 2005(Travis Oliphant) yılında hayata geçirilmiştir.

**Listelere benzerdir, farkı; verimli veri saklama ve vektörel operasyonlardır.**

# Neden Numpy?
optimizasyon anlamında daha iyi

veri tutma konusunda daha hesaplı

In [2]:
a= [1,2,3] # 3 tane integer değeri var
b= [3,4,5]


In [3]:
ab = []
for i in range(0,len(a)):
    ab.append(a[i]*b[i])
    
ab

[3, 8, 15]

In [3]:
import numpy as np

In [5]:
a = np.array([1,2,3]) ## tek bir veri tipi var çok daha hesaplı.
b=np.array([3,4,5])


In [6]:
a*b

array([ 3,  8, 15])

Numpy arrayleri oluşturma

In [7]:
a= np.array([1,2,3])

In [8]:
type(a)

numpy.ndarray

In [9]:
np.array([3.14,4,2,13], dtype='float32')

array([ 3.14,  4.  ,  2.  , 13.  ], dtype=float32)

In [10]:
np.array([3.9,4,2,13], dtype='int')

array([ 3,  4,  2, 13])

## sıfırdan array oluşturma

In [11]:
np.zeros((10,2),dtype = int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [12]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3,5),dtype= int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.full((3,5),3.2, dtype=int)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [12]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [11]:
np.linspace(0,10,10) ## eşit aralıklara bölüyor garip bişiy matplot lible anlamlı hale  geliyor

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [16]:
(np.linspace)

Object `(np.linspace)` not found.


In [524]:
np.random.normal(10,4,(3,4))

array([[14.56475006,  7.89483379, 12.13847006,  8.07953618],
       [13.88608613,  5.29255424,  2.92913857,  9.8310192 ],
       [16.72588115, 13.53091401,  8.0321539 , 13.33048239]])

In [19]:
np.random.randint(0,10, (3,3))

array([[0, 0, 2],
       [1, 3, 7],
       [6, 9, 0]])

Tek boyutlu arrayin karşılığı vektördür , iki boyutlu arrayin karşılığı matrisdir.

#numpy özellikleri
* ndim: boyut sayısı

* shape: boyut bilgisi

* size: toplam eleman sayısı

* dtype: array veri tipi

In [25]:
np.random.randint(10,size=12)

array([2, 1, 8, 7, 5, 2, 3, 8, 3, 0, 5, 1])

In [26]:
a= np.random.randint(10,size=12)

In [27]:
a

array([1, 0, 5, 3, 7, 6, 9, 2, 8, 4, 4, 0])

In [28]:
a.ndim

1

In [29]:
a.shape

(12,)

In [30]:
a.size

12

In [31]:
a.dtype

dtype('int32')

In [32]:
b= np.random.randint(10,size=(3,5))

In [33]:
b

array([[7, 8, 6, 8, 8],
       [9, 6, 4, 6, 1],
       [3, 2, 7, 7, 6]])

In [35]:
b.ndim

2

In [36]:
b.shape

(3, 5)

In [37]:
b.size

15

In [38]:
b.dtype

dtype('int32')

# Yenidden Şekillendirme (reshaping)

In [42]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
a = np.arange(1,10)

In [48]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a.ndim

1

In [53]:
b=a.reshape((1,9))

In [54]:
b.ndim

2

In [55]:
a.ndim

1

# Birleştirme Concantenation

In [56]:
x = np.array([1,2,3])
y= np.array([4,5,6])

In [58]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [59]:
z= np.array([7,8,9])

In [60]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
a= np.array([[1,2,3],
             [4,5,6,]
            ])

In [62]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [64]:
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [66]:
np.concatenate([a,a],axis=0) ## default olarak 0'mış, axis=1 stün bazında birleştirir, axis=0 satırları

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

# Ayrıştırma Ayırma (Splitting)

In [4]:
x= np.array([1,2,3,99,99,3,2,1])

In [69]:
np.split(x,[3,5]) # 3 e kadar, 5 e kadar , x e kadar , n ye kadar

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [75]:
a,b,c= np.split(x,[3,5]) # bunu ilk kez kullandık

In [76]:
a

array([1, 2, 3])

In [77]:
b

array([99, 99])

In [78]:
c

array([3, 2, 1])

# iki boyutlu ayırma 

In [5]:
m= np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
ust,alt= np.vsplit(m, [2]) #dikey yan yana

np.vsplit

Split an array into multiple sub-arrays vertically (row-wise).

In [16]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.hsplit(m,[2]) ## yatay yan yana

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

np.hsplit

Split an array into multiple sub-arrays horizontally (column-wise).

In [24]:
sag,sol= np.hsplit(m, [2]) #yatay yan yana

In [25]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [26]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [27]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

# Sıralama Sorting

In [103]:
v= np.array([2,1,4,3,5])

In [104]:
v

array([2, 1, 4, 3, 5])

In [110]:
np.sort(v) # ölümcül fonksiyon değil

array([1, 2, 3, 4, 5])

In [107]:
v

array([2, 1, 4, 3, 5])

In [113]:
v.sort() #ölümcül fonksiyon, yani yapıyı değiştiriyor, yeniden atama yapmadan.

In [114]:
v

array([1, 2, 3, 4, 5])

## iki boyutlu değer sıralama

In [31]:
m= np.random.normal(20,5, (3,3))

In [32]:
m

array([[25.70029893, 22.07695572, 13.65410781],
       [31.06603302, 20.46214778, 20.84304699],
       [25.87528743, 24.6333743 , 15.76303916]])

In [33]:
np.sort(m, axis=1)

array([[13.65410781, 22.07695572, 25.70029893],
       [20.46214778, 20.84304699, 31.06603302],
       [15.76303916, 24.6333743 , 25.87528743]])

In [34]:
np.sort(m, axis=0)

array([[25.70029893, 20.46214778, 13.65410781],
       [25.87528743, 22.07695572, 15.76303916],
       [31.06603302, 24.6333743 , 20.84304699]])

In [35]:
np.sort(m,axis=-1)

array([[13.65410781, 22.07695572, 25.70029893],
       [20.46214778, 20.84304699, 31.06603302],
       [15.76303916, 24.6333743 , 25.87528743]])

# Eleman İşlemleri

In [38]:
# index ile elemana erişmek
a= np.random.randint(10, size=10)
a

array([0, 7, 8, 6, 2, 9, 9, 0, 6, 6])

In [39]:
 a[0]

0

In [40]:
a[-1]

6

In [41]:
a[0]= 100

In [42]:
a[2-3]

6

In [131]:
# iki boyutlu
m= np.random.randint(10, size=(3,5))

In [132]:
m

array([[6, 6, 6, 3, 3],
       [1, 4, 3, 3, 9],
       [7, 5, 0, 1, 9]])

In [133]:
m[0,0]

6

In [134]:
m[1,2]

3

In [135]:
m[1,4]

9

In [142]:
m[1,4] = 99

In [143]:
m

array([[ 6,  6,  6,  3,  3],
       [ 1,  4,  3,  3, 99],
       [ 7,  5,  0,  1,  9]])

In [146]:
m[1,4]= 99.6

In [147]:
m

array([[ 6,  6,  6,  3,  3],
       [ 1,  4,  3,  3, 99],
       [ 7,  5,  0,  1,  9]])

# array alt küme işlemleri ve Slicing

In [44]:
a= np.arange(20,30)

In [45]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [152]:
a[0:3] # x den y ye kadar git

array([20, 21, 22])

In [155]:
a[:3] # y ye kadar git

array([20, 21, 22])

In [157]:
a[3:] # x den sona kadar git

array([23, 24, 25, 26, 27, 28, 29])

In [62]:
a[1::2] ##ikişer ikişer ilerlemiş

array([21, 23, 25, 27, 29])

In [162]:
a[2::2]

array([22, 24, 26, 28])

In [163]:
a[0::2]

array([20, 22, 24, 26, 28])

In [165]:
a[0::3]

array([20, 23, 26, 29])

# slice işlemleri

In [72]:
m = np.random.randint(10,size=(5,5))

In [73]:
m

array([[9, 7, 8, 2, 1],
       [8, 1, 4, 0, 3],
       [5, 8, 1, 2, 7],
       [7, 6, 7, 4, 5],
       [2, 8, 3, 0, 0]])

In [74]:
m[:,0]

array([9, 8, 5, 7, 2])

In [77]:
m[0,:]

array([9, 7, 8, 2, 1])

In [560]:
m[:,1]

array([ 1,  5,  9, 13])

In [78]:
m[0:2, 0:3,]

array([[9, 7, 8],
       [8, 1, 4]])

In [568]:
m[3,2:]

array([14, 15])

In [569]:
m[3:]

array([[12, 13, 14, 15]])

In [190]:
m[1:3, 0:3]

array([[1, 2, 2],
       [5, 9, 1]])

## alt küme üzerinde İşlem yapmak

In [570]:
a = np.random.randint(10,size= (5,5))
a

array([[8, 1, 6, 0, 3],
       [7, 5, 0, 8, 9],
       [8, 5, 1, 9, 4],
       [6, 2, 6, 3, 3],
       [7, 3, 2, 8, 5]])

In [573]:
alt_a = a[0:4, 0:3]
alt_a

array([[8, 1, 6],
       [7, 5, 0],
       [8, 5, 1],
       [6, 2, 6]])


m= np.array([[4, 7, 4, 5, 9],
            [2, 5, 0, 7, 7],
            [1, 9, 0, 8, 2]])

m[:2,:3]

In [353]:
m=np.array([[[7, 9],

[4, 0],
[5, 9]],

[[4, 8],
[6, 4],
[4, 5]],

[[2, 2],
[8, 2],
[0, 2]]])
m

v = np.array([7, 3, 4, 7, 0, 9, 3, 2, 9, 2])

v[-2]

9

In [197]:
alt_a

array([[3, 6],
       [6, 8],
       [7, 3]])

In [198]:
alt_a [0,0] = 99999
alt_a [1,1] = 8888

In [199]:
alt_a

array([[99999,     6],
       [    6,  8888],
       [    7,     3]])

In [200]:
a

array([[99999,     6,     3,     6,     8],
       [    6,  8888,     9,     2,     4],
       [    7,     3,     3,     2,     0],
       [    3,     0,     2,     6,     4],
       [    8,     9,     1,     7,     3]])

In [574]:
b = np.random.randint(10,size= (5,5))
b


array([[2, 4, 8, 0, 5],
       [2, 3, 7, 2, 6],
       [1, 2, 4, 7, 2],
       [3, 5, 8, 4, 3],
       [5, 8, 0, 5, 3]])

In [575]:
 b[0:3, 0:2]

array([[2, 4],
       [2, 3],
       [1, 2]])

In [576]:
b

array([[2, 4, 8, 0, 5],
       [2, 3, 7, 2, 6],
       [1, 2, 4, 7, 2],
       [3, 5, 8, 4, 3],
       [5, 8, 0, 5, 3]])

In [577]:
alt_b = b[0:3, 0:2].copy()

In [578]:
alt_b

array([[2, 4],
       [2, 3],
       [1, 2]])

In [206]:
alt_b [0,0] = 12
alt_b [1,1] = 13

In [208]:
alt_b

array([[12,  0],
       [ 0, 13],
       [ 9,  5]])

In [210]:
b  ## copy methodu ile matrisin kendisini değiştirmesini engelledik, ölümcül olmasını istemediğimiz için bu özelliği kullandık.

array([[9, 0, 7, 0, 1],
       [0, 4, 5, 4, 4],
       [9, 5, 9, 5, 6],
       [5, 9, 7, 0, 9],
       [4, 0, 5, 2, 3]])

## Fancy Index ile elemanlara erişmke

In [211]:
### en önemli kavram
v= np.arange(0,30,3)

In [212]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [216]:
v[1],v[3],v[5]

(3, 9, 15)

In [214]:
al_getir=[1,3,5]

In [217]:
v[al_getir] ## buna fancy index diyolar

array([ 3,  9, 15])

In [218]:
## iki boyutta fancy
m= np.arange(9).reshape((3,3))

In [219]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [220]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [222]:
m[satir,sutun]

array([1, 5])

In [223]:
m[0,[1,2]]

array([1, 2])

In [226]:
m[[0,0],[1,2]]

array([1, 2])

In [227]:
m[[0,1],[1,2]]

array([1, 5])

In [228]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Koşullu eleman işlemleri

In [229]:
v= np.array([1,2,3,4,5])

In [230]:
v

array([1, 2, 3, 4, 5])

In [231]:
v<5

array([ True,  True,  True,  True, False])

In [232]:
v>5

array([False, False, False, False, False])

In [235]:
v<=3 # yani her bir elemanı verdiğimiz state e göre kontrol edip true false döndürebiliyoruz.

array([ True,  True,  True, False, False])

In [237]:
v[v<3] ##  fancy yazım tarzı ile de kontrol işlemi sağlanabiliyor. güzel özellik

array([1, 2])

In [238]:
v[v<=3]

array([1, 2, 3])

In [239]:
v[v==3]

array([3])

In [240]:
v[v!=3]

array([1, 2, 4, 5])

In [241]:
v[v>=3]

array([3, 4, 5])

In [242]:
v*2

array([ 2,  4,  6,  8, 10])

In [243]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [244]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [245]:
v**2

array([ 1,  4,  9, 16, 25])

# Matematiksel İşlemler

In [247]:
v= np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

In [249]:
v-1

array([0, 1, 2, 3, 4])

In [250]:
v*5

array([ 5, 10, 15, 20, 25])

In [251]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [256]:
(v*2/10)+ 60

array([60.2, 60.4, 60.6, 60.8, 61. ])

# ufunc

In [257]:
np.subtract(v,1)   # v-1 demek

array([0, 1, 2, 3, 4])

In [258]:
np.multiply(v,2)

array([ 2,  4,  6,  8, 10])

In [260]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [262]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [263]:
np.power(v,3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [265]:
v%2

array([1, 0, 1, 0, 1], dtype=int32)

In [266]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [268]:
np.absolute(np.array([-3])) # mutlak değer 

array([3])

In [269]:
# trigonometrik func
np.sin(360)

0.9589157234143065

In [275]:
np.cos(30)

0.15425144988758405

In [280]:
np.tan(60)

0.320040389379563

In [278]:
1/np.tan(60)

3.124605622242308

In [281]:
v = np.array([1,2,3])

In [286]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [288]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [291]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [293]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\kazan\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\kazan\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x

In [295]:
np.lookfor('trigonometry')

Search results for 'trigonometry'
---------------------------------
numpy.sin
    Trigonometric sine, element-wise.
numpy.ma.sin
    Trigonometric sine, element-wise.


# cheat sheet 
kopya kağıdı

In [297]:
v

array([1, 2, 3])

In [296]:
np.mean(v)

2.0

In [298]:
np.sum(v)

6

In [299]:
np.min(v)

1

In [300]:
np.max(v)

3

In [301]:
np.var(v) # returns varience

0.6666666666666666

In [304]:
np.std(v,axis=0) #returns Starndart deviation

0.816496580927726

In [306]:
np.corrcoef(v) # correlation coefficient of the array

1.0

## numpy ile iki bilinmeyenli denklem çözme

* 5* x0+ x1 =12
* x0+3*x1=10

In [316]:
a= np.array([[5,1],[1,3]])
b= np.array([12,10])

In [317]:
a

array([[5, 1],
       [1, 3]])

In [318]:
b

array([12, 10])

In [319]:
x=np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])

 # Bölüm sonu değerlendirmesi
 * Güzel modül , kütüphane
 * çok temeldir
 * hoştur
 * görmüş olduğumuz ; oluşturma(array()), biçimlendirme(reshape()) , yeniden sıralama(arrange()) ,birleştirme(concatenate()) , ayırma(split()), sıralama(sort())
 
 * index ile elemana erişme, slicing, fancy index, koşullu operasyonlar

In [584]:
a = np.array([[4, 7, 4, 5, 9],

            [2, 5, 0, 7, 7],

            [1, 9, 0, 8, 2]])

In [326]:
v = np.array([ 0, 3, 6, 9, 12, 15, 18, 21, 24, 27])



v[[4,2,3]]

array([12,  6,  9])

In [587]:
np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [328]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [333]:
v.dtype

dtype('int32')

# Pandas
* Panel Data
* Ekonometrik ve finansal çalışmalar için doğmuştur.
* zaman indexini önemseyen veri tutumları için iyi
* Veri Manipülasyou ve veri analizi için yazılmış açık kaynak kodlu bir python kütphanesidir.
* Ekonometri ve Finansal çalışmalar için doğmuştur.
* Temeli 2008 yılında atılmıştır.
* R DataFrame yapısını Python dünyasına taşımış ve DataFrame'ler üzerinde hızlı ve etkili çalışabilme imkanı sağlamıştır

# Pandas serisi olutşruma

In [354]:
import pandas as pd

In [367]:
seri1=pd.Series([1,2,3,4,5])

In [588]:
seri2 = pd.Series([[1,2,3,4,5],
                   [6,7,8,9,10]])

In [371]:
type(seri2)

pandas.core.series.Series

In [375]:
seri.axes

[RangeIndex(start=0, stop=2, step=1)]

In [374]:
seri1.axes

[RangeIndex(start=0, stop=5, step=1)]

In [377]:
seri1.dtype

dtype('int64')

In [378]:
seri2.dtype

dtype('O')

In [380]:
seri1.ndim

1

In [382]:
df= pd.DataFrame([[1,2,3,4,5],[6,7,8,9,10]])

In [383]:
df

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [384]:
df.head()

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [385]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       2 non-null      int64
 1   1       2 non-null      int64
 2   2       2 non-null      int64
 3   3       2 non-null      int64
 4   4       2 non-null      int64
dtypes: int64(5)
memory usage: 208.0 bytes


In [386]:
pd.Series([998,875,120,65,443])

0    998
1    875
2    120
3     65
4    443
dtype: int64

In [390]:
pd.Series([998,875,120,65,443], index=['a','b','altıms','2',8])

a         998
b         875
altıms    120
2          65
8         443
dtype: int64

In [392]:
pd.Series([998,875,120,65,443], index=[1,2,3,4,5])

1    998
2    875
3    120
4     65
5    443
dtype: int64

In [393]:
seri= pd.Series([998,875,120,65,443], index=['a','b','altıms','2',8])

In [394]:
seri['a']

998

In [395]:
seri['a':'2']

a         998
b         875
altıms    120
2          65
dtype: int64

# sözlük üzerinden liste oluşturmak

In [589]:
sozluk= {'Reg': 10, 
        'log': 11,
        'cart': 'asdadsa'}

sozluk_seri= pd.Series(sozluk)

In [400]:
sozluk_seri

Reg          10
log          11
cart    asdadsa
dtype: object

## iki seriyi birleştirerek pandas serisi oluşturma

In [404]:
pd.concat([seri,sozluk_seri])

a             998
b             875
altıms        120
2              65
8             443
Reg            10
log            11
cart      asdadsa
dtype: object

# Eleman İşlemleri

In [405]:
a = np.array([1,2,33,444,75])
seri = pd.Series(a)
seri

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [432]:
a[1:4] #1. indexden den 4.index e "kadar"

array([  2,  33, 444])

In [407]:
seri.info()

<class 'pandas.core.series.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int32
dtypes: int32(1)
memory usage: 148.0 bytes


In [408]:
seri[0]

1

In [409]:
seri[0:3]

0     1
1     2
2    33
dtype: int32

## Farklılaştığı nokta

In [410]:
seri= pd.Series([121,200,150,99],
                index=['reg','loj','cart','rf'])

In [411]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [412]:
seri.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

In [413]:
seri.keys

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [419]:
list(seri.items())

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [420]:
seri.values

array([121, 200, 150,  99], dtype=int64)

In [421]:
seri

reg     121
loj     200
cart    150
rf       99
dtype: int64

* Eleman sorgulama

In [424]:
'reg' in seri # serinin içinde böyle bir index/key varmı yok mu diye sorguluyor.

True

In [423]:
'yucaib' in seri

False

In [425]:
seri['reg']

121

* fancy eleman

In [427]:
seri[['reg','rf']]

reg    121
rf      99
dtype: int64

In [428]:
seri['reg']=130

In [429]:
seri['reg']

130

* slice ile bir seçim

In [438]:
seri['reg':'loj'] # burda loj dahil yapıyor anlamadım tam olarak bu da bir farklılık sanırsam

reg    130
loj    200
dtype: int64

In [433]:
seri

reg     130
loj     200
cart    150
rf       99
dtype: int64

## Pandas DataFrame

In [439]:
l= [1,2,39,46,55,67]

In [440]:
l

[1, 2, 39, 46, 55, 67]

In [442]:
pd.DataFrame(l, columns=['degisken isim'])

degisken isim
0              1
1              2
2             39
3             46
4             55
5             67

In [446]:
m= np.arange(1,10).reshape(3,3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [448]:
pd.DataFrame(m, columns=['var1','var2','var3'])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

df isimlendirme

In [450]:
df = pd.DataFrame(m, columns=['var1','var2','var3'])


In [452]:
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [455]:
df.columns= ('deg1','deg2','deg3') # böyle de column isimlerini değiştirebiliriz.

In [456]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [457]:
type(df)

pandas.core.frame.DataFrame

In [460]:
df.axes # sıfırdan başlayıp 3 e kadar gidiyor 1 er 1 er artıyor diyor RangeIndex(start=0, stop=3, step=1) burada

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [461]:
df.shape

(3, 3)

In [462]:
df.ndim # dimension boyut 2 boyutlu

2

In [463]:
df.size

9

In [464]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [465]:
type(df.values) ##sadece değerleri çekti numpy arrayine dönüştürmüş oluyoruz bu şekilde pandas objesini

numpy.ndarray

In [466]:
df.head()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [467]:
df.tail(2) # sondan itibaren itemler

deg1  deg2  deg3
1     4     5     6
2     7     8     9

In [472]:
a = np.array([1,2,3,4,5])

In [476]:
pd.DataFrame(a, columns= ['deg1'])

deg1
0     1
1     2
2     3
3     4
4     5

# pandas ile Eleman işlemleri 

In [477]:
s1 = np.random.randint(10,size=5)
s2 = np.random.randint(10,size=5)
s3 = np.random.randint(10,size=5)

In [479]:
sozluk = {'var1': s1, 'var2': s2, 'var3': s3}
sozluk

{'var1': array([1, 3, 8, 3, 8]),
 'var2': array([7, 3, 8, 0, 5]),
 'var3': array([0, 9, 9, 7, 4])}

In [480]:
df=pd.DataFrame(sozluk)

In [482]:
df

var1  var2  var3
0     1     7     0
1     3     3     9
2     8     8     9
3     3     0     7
4     8     5     4

In [484]:
df[:2]

var1  var2  var3
0     1     7     0
1     3     3     9

In [486]:
df.index= ['a','b','c','d','e']

In [487]:
df

var1  var2  var3
a     1     7     0
b     3     3     9
c     8     8     9
d     3     0     7
e     8     5     4

In [488]:
## silme
df.drop('a',axis=0)

var1  var2  var3
b     3     3     9
c     8     8     9
d     3     0     7
e     8     5     4

In [489]:
df # drop direk verisetinin yapısının üzerinde bir değişiklik olmadı.

var1  var2  var3
a     1     7     0
b     3     3     9
c     8     8     9
d     3     0     7
e     8     5     4

In [491]:
df.drop('a',axis=0,inplace=True)

In [492]:
df

var1  var2  var3
b     3     3     9
c     8     8     9
d     3     0     7
e     8     5     4

In [493]:
l=[ 'c','e']

df.drop(l,axis=0)

var1  var2  var3
b     3     3     9
d     3     0     7

In [494]:
df

var1  var2  var3
b     3     3     9
c     8     8     9
d     3     0     7
e     8     5     4

In [496]:
  'var1' in df

True

In [497]:
#sorgulama
l=['var1','var2','var3','var4']

for i in l:
    print(i in df)

True
True
True
False


In [498]:
df

var1  var2  var3
b     3     3     9
c     8     8     9
d     3     0     7
e     8     5     4

In [503]:
df['var4'] = [1,2,5,2]

In [505]:
df


var1  var2  var3  var4
b     3     3     9     1
c     8     8     9     2
d     3     0     7     5
e     8     5     4     2

In [506]:
df['var5'] = df['var2']+df['var4']

In [507]:
df

var1  var2  var3  var4  var5
b     3     3     9     1     4
c     8     8     9     2    10
d     3     0     7     5     5
e     8     5     4     2     7

In [509]:
df.drop('var4', axis=1, inplace= True)

In [510]:
df

var1  var2  var3  var5
b     3     3     9     4
c     8     8     9    10
d     3     0     7     5
e     8     5     4     7

In [511]:
l=['var3','var5']
df.drop(l, axis=1, inplace= True)

In [512]:
df

var1  var2
b     3     3
c     8     8
d     3     0
e     8     5

# Gözlem ve Değişken Seçimi (Loc ve iLoc)

In [590]:
import pandas as pd
import numpy as np

In [643]:
m= np.random.randint(1,30, size=(10,3)) ##(satır,stün)

df= pd.DataFrame(m, columns = ['var1','var2','var3'])
df

var1  var2  var3
0     6    29    22
1    21    10    28
2    11     4     9
3     3    20    17
4     7    19    25
5    27    20    16
6    20     9     3
7    23     3    28
8    12    17    28
9    20    16    12

In [596]:
#loc: Tanımlandığı şekli ile seçim yapmak için kullanılır.

In [603]:
df.loc[0:3]  ## sıfırdan 3 e kadar 3 dahil seçim yaptı

var1  var2  var3
0     6    22    23
1     6    13    24
2     4    17    19
3    16    28    16

In [604]:
#iloc: aloşık olduğumuz index mantığı ile seçim yapar

In [606]:
df.iloc[0:3] ### 0'dan 3 "e kadar"

var1  var2  var3
0     6    22    23
1     6    13    24
2     4    17    19

In [608]:
df

var1  var2  var3
0     6    22    23
1     6    13    24
2     4    17    19
3    16    28    16
4     4    27     2
5    26    27    14
6    10     9     9
7    17    25    13
8    16    23    23
9     2    21    20

In [607]:
df.iloc[0,0]

6

In [610]:
df.iloc[:3,:2] # 3. (index olarak) satıra kadar ve 2. (index olarak yani) stüna kadar

var1  var2
0     6    22
1     6    13
2     4    17

In [621]:
df.loc[:3,: 'var3']

var1  var2  var3
0     6    22    23
1     6    13    24
2     4    17    19
3    16    28    16

In [619]:
df.loc[:3,] # 3 e kadar

var1  var2  var3
0     6    22    23
1     6    13    24
2     4    17    19
3    16    28    16

In [625]:
df.iloc[0:3] ['var3']

0    23
1    24
2    19
Name: var3, dtype: int32

In [626]:
df.iloc[0:3] 

var1  var2  var3
0     6    22    23
1     6    13    24
2     4    17    19

## Koşullu eleman işlemleri

In [628]:
df

var1  var2  var3
0     6    22    23
1     6    13    24
2     4    17    19
3    16    28    16
4     4    27     2
5    26    27    14
6    10     9     9
7    17    25    13
8    16    23    23
9     2    21    20

In [630]:
df['var1'][0:2]

0    6
1    6
Name: var1, dtype: int32

In [634]:
df.loc[:6,: 'var3']

var1  var2  var3
0     6    22    23
1     6    13    24
2     4    17    19
3    16    28    16
4     4    27     2
5    26    27    14
6    10     9     9

In [641]:
df[df.var1 > 15] ['var1']

3    16
5    26
7    17
8    16
Name: var1, dtype: int32

In [644]:
df[ (df.var1 > 15) & (df.var3<5) ]

var1  var2  var3
6    20     9     3

In [648]:
df.loc[ (df.var1 > 15),["var1", "var2"] ]

var1  var2
1    21    10
5    27    20
6    20     9
7    23     3
9    20    16

In [652]:
df[ (df.var1 > 15) ] [ ["var1", "var2"]]

var1  var2
1    21    10
5    27    20
6    20     9
7    23     3
9    20    16

In [653]:
df.iloc[0:3] 

var1  var2  var3
0     6    29    22
1    21    10    28
2    11     4     9

In [658]:
df[0:3] [['var1','var2']]

var1  var2
0     6    29
1    21    10
2    11     4

##  basitleştirilmiş Join işlemleri

In [83]:
import numpy as np
import pandas as pd

m= np.random.randint(1,30,size=(5,3))

df1= pd.DataFrame(m, columns = ['var1','var2','var3'])
df1

var1  var2  var3
0    23    13     3
1    17    10    20
2    18    14     5
3    15    22    20
4     6     4    16

In [84]:
df2 = 100+df1

In [85]:
df2

var1  var2  var3
0   123   113   103
1   117   110   120
2   118   114   105
3   115   122   120
4   106   104   116

In [86]:
pd.concat([df1,df2])

var1  var2  var3
0    23    13     3
1    17    10    20
2    18    14     5
3    15    22    20
4     6     4    16
0   123   113   103
1   117   110   120
2   118   114   105
3   115   122   120
4   106   104   116

In [87]:
pd.concat([df1,df2], ignore_index= True)

var1  var2  var3
0    23    13     3
1    17    10    20
2    18    14     5
3    15    22    20
4     6     4    16
5   123   113   103
6   117   110   120
7   118   114   105
8   115   122   120
9   106   104   116

In [88]:
## column adlarını değişitirp tekrar deneyelim
df1.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [89]:
df2.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [90]:
df2.columns= ["var1","var2","deg3"]

In [91]:
pd.concat([df1,df2,],ignore_index=True) ## yani birbiri ile tamamlanamayacak olduğu için, columnun eksik olduğu veri setine NAN değeri giriyor.

var1  var2  var3   deg3
0    23    13   3.0    NaN
1    17    10  20.0    NaN
2    18    14   5.0    NaN
3    15    22  20.0    NaN
4     6     4  16.0    NaN
5   123   113   NaN  103.0
6   117   110   NaN  120.0
7   118   114   NaN  105.0
8   115   122   NaN  120.0
9   106   104   NaN  116.0

In [92]:
pd.concat([df1,df2 ],join='inner')

var1  var2
0    23    13
1    17    10
2    18    14
3    15    22
4     6     4
0   123   113
1   117   110
2   118   114
3   115   122
4   106   104

In [93]:
pd.concat([df1,df2] , join_axes= [df2.columns]) ##deprecated since 0.25 version

TypeError: concat() got an unexpected keyword argument 'join_axes'

In [94]:
? pd.concat

Signature:
 pd.concat(
    objs: 'Iterable[NDFrame] | Mapping[HashableT, NDFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool' = True,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis.

Allows optional set logic along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
    they are all None in which case a ValueError will be raised.
axis : {0/'index', 1/'co

## ileri birleştirme işlemleri


In [96]:
df1= pd.DataFrame({'calisanlar': ['ali','veli','ayse','fatma'],
                  'gurup':['Muhasebe', 'Muhendsilik', 'Muhendsilik','İK'],
                  })
df1

calisanlar        gurup
0        ali     Muhasebe
1       veli  Muhendsilik
2       ayse  Muhendsilik
3      fatma           İK

In [97]:
df2= pd.DataFrame({'calisanlar': ['ali','veli','ayse','fatma'],
                  'ilk giris':[2010,2009,2014,2019],
                  })
df2

calisanlar  ilk giris
0        ali       2010
1       veli       2009
2       ayse       2014
3      fatma       2019

In [108]:
pd.merge(df1,df2)

calisanlar        gurup  ilk giris
0        ali     Muhasebe       2010
1       veli  Muhendsilik       2009
2       ayse  Muhendsilik       2014
3      fatma           İK       2019

In [99]:
df3=pd.merge(df1,df2, on='calisanlar') # çalışanlar üzeridnen birleştirdi ama normalde de öyle birleştirmişti çünkü onu tespit etti, en başta geliyordu.

In [100]:
df3

calisanlar        gurup  ilk giris
0        ali     Muhasebe       2010
1       veli  Muhendsilik       2009
2       ayse  Muhendsilik       2014
3      fatma           İK       2019

In [101]:
df4= pd.DataFrame({'gurup':['Muhasebe', 'Muhendsilik','İK'],
                  'mudur': ['Caner','Mustafa', 'Berkcan']
                  })
df4

gurup    mudur
0     Muhasebe    Caner
1  Muhendsilik  Mustafa
2           İK  Berkcan

In [102]:
df5= pd.merge(df3,df4, on='gurup') ## one to many oldu meela mühendislik için mmühendislerin müdür Mustafa olduuuu.

In [103]:
df5

calisanlar        gurup  ilk giris    mudur
0        ali     Muhasebe       2010    Caner
1       veli  Muhendsilik       2009  Mustafa
2       ayse  Muhendsilik       2014  Mustafa
3      fatma           İK       2019  Berkcan

In [104]:
### çoktan çoka
df6= pd.DataFrame({'gurup':['Muhasebe', 'Muhasebe', 'Muhendsilik', 'Muhendsilik','İK','İK'],
                  'yetenekler': ['matematik','excel', 'kodlama', 'linux', 'excel','yonetim']
                  })
df6

gurup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendsilik    kodlama
3  Muhendsilik      linux
4           İK      excel
5           İK    yonetim

In [105]:
pd.merge(df5,df6, on='gurup')

calisanlar        gurup  ilk giris    mudur yetenekler
0        ali     Muhasebe       2010    Caner  matematik
1        ali     Muhasebe       2010    Caner      excel
2       veli  Muhendsilik       2009  Mustafa    kodlama
3       veli  Muhendsilik       2009  Mustafa      linux
4       ayse  Muhendsilik       2014  Mustafa    kodlama
5       ayse  Muhendsilik       2014  Mustafa      linux
6      fatma           İK       2019  Berkcan      excel
7      fatma           İK       2019  Berkcan    yonetim