# Veri Bilimi için İstatistik
## Örneklem, Örneklem Dağılımı, Merkezi Limit Teoremi

In [42]:
# örneklem
import numpy as np

In [53]:
populasyon = np.random.randint(0,80,10000)

In [54]:
populasyon[0:10]

array([54, 42, 49, 63, 14, 76, 41, 64, 68, 26])

In [55]:
# örneklem cekimi
np.random.seed(10)
orneklem= np.random.choice(a= populasyon, size=100)

In [56]:
orneklem[:10]

array([17, 32, 69, 47, 61,  3, 78, 61, 52, 36])

In [57]:
orneklem.mean()

44.38

In [58]:
populasyon.mean()

39.2299

In [59]:
#örneklem dağılımı
np.random.seed(10)
orneklem1 = np.random.choice(a= populasyon, size =100)
orneklem2 = np.random.choice(a= populasyon, size =100)
orneklem3 = np.random.choice(a= populasyon, size =100)
orneklem4 = np.random.choice(a= populasyon, size =100)
orneklem5 = np.random.choice(a= populasyon, size =100)
orneklem6 = np.random.choice(a= populasyon, size =100)
orneklem7 = np.random.choice(a= populasyon, size =100)
orneklem8 = np.random.choice(a= populasyon, size =100)
orneklem9 = np.random.choice(a= populasyon, size =100)
orneklem10 = np.random.choice(a= populasyon, size =100)


In [61]:
(orneklem1.mean()+orneklem2.mean()+orneklem3.mean()+orneklem4.mean()+orneklem5.mean()+orneklem6.mean()
 +orneklem7.mean()+orneklem8.mean()+orneklem9.mean()+orneklem10.mean()) / 10

39.800000000000004

In [62]:
orneklem7.mean()

36.77

In [63]:
orneklem10.mean()

39.05

# Betimsel istatik
## Ortalama , medyan , mod, kartiller, değişim aralığı, standart Sapma, Kovaryans , Korelasyon

### varyans, ortalama etrafında dağılımın ölçüsü, SS'nin karesi
### kovaryans iki değişken arasındaki ilişkinin değişkenlik ölçüsüdür.
### cov(X,Y)= E[(X-E[X])(Y-E[Y])]
### Korelasyon iki değişken arasındaki ilişkiyi, ilişkinin anlamlı olup olmadığını, ilişkinin şiddetini ve yönünü ifade eden istatiksel bir tekniktir.

In [6]:
import seaborn as sns
tips = sns.load_dataset("tips")
df= tips.copy()

In [7]:
df.describe().T

count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [71]:
!pip install researchpy

In [8]:
import researchpy as rp

In [9]:
rp.summary_cont(df[['total_bill', 'tip','size']])

C:\Users\ycanf\anaconda3\Lib\site-packages\researchpy\summary.py:60: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for ix, df_col in group1.iteritems():


Variable      N     Mean      SD      SE  95% Conf.  Interval
0  total_bill  244.0  19.7859  8.9024  0.5699    18.6633   20.9086
1         tip  244.0   2.9983  1.3836  0.0886     2.8238    3.1728
2        size  244.0   2.5697  0.9511  0.0609     2.4497    2.6896

In [15]:
rp.summary_cat(df[['sex', 'smoker','day']])

C:\Users\ycanf\anaconda3\Lib\site-packages\researchpy\summary.py:225: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for ix, df_col in group1.iteritems():


Variable Outcome  Count  Percent
0      sex    Male    157    64.34
1           Female     87    35.66
2   smoker      No    151    61.89
3              Yes     93    38.11
4      day     Sat     87    35.66
5              Sun     76    31.15
6             Thur     62    25.41
7              Fri     19     7.79

In [16]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [83]:
df[["tip",'total_bill']].cov() # kovaryans değişkenlerin ilişkilerine ilişkin değişkenlik ölçüsü veriyor

tip  total_bill
tip         1.914455    8.323502
total_bill  8.323502   79.252939

In [84]:
df[["tip",'total_bill']].corr()

tip  total_bill
tip         1.000000    0.675734
total_bill  0.675734    1.000000

## İş uygulaması Fiyat Stratejisi Karar Destek
### Problem: Ceo Fiyat belirleme konusunda "bilimsel bir dayanak ve esneklik" istiyor

### Detaylar : 
### Satıcı, alıcı ve bir ürün var
### Alıcılara ürüne ne kadar ücret öderdiniz diye soruluyor. Kimse birbirinin teklif ettiği fiyatları göremiyor.
### Optimum fiyat bilimsel ve esnek olarak bulunmak isteniyor(yani güven aralığı)

In [19]:
import numpy as np
fiyatlar = np.random.randint(10,110,1000)

In [20]:
fiyatlar

array([ 18,  32,  46,  66,  30,  20,  28,  17,  38,  76,  10,  39,  43,
        40,  76,  92,  89,  17,  65,  43,  91,  41,  20,  66,  61,  87,
        57,  59,  87,  56,  17,  77,  75,  16,  76,  61,  54, 109,  37,
       109, 104,  76,  94,  97,  88,  87,  59,  84,  29,  11,  39,  74,
        62,  95, 107,  72,  22, 109,  76, 100,  87,  72,  50,  76,  47,
        97,  69,  67,  17,  20,  56,  97, 107,  74, 104,  26,  38,  76,
        49,  16,  78,  56,  47,  81,  22,  29,  67,  18,  19,  44,  56,
        90, 104, 107,  86,  83,  13,  71, 103,  46,  10,  22,  77,  27,
       105,  70,  25,  83,  69,  22,  82,  43,  38,  52,  40,  48,  49,
        50,  78,  63,  92,  85,  91,  86,  33,  61,  39,  51,  21,  61,
        48,  11,  83,  83,  65, 100,  47,  79,  67,  43,  17,  69,  18,
        61,  90,  56,  50,  54,  67,  76,  97,  94,  21,  59,  97,  83,
        59,  34,  45,  39, 103,  14,  63,  76,  99,  61,  71,  68,  67,
        67,  13,  89, 107,  12,  43,  21,  86,  23,  57,  38,  1

In [22]:
fiyatlar.mean()

59.738

In [23]:
import statsmodels.stats.api as sms

In [24]:
sms.DescrStatsW(fiyatlar).tconfint_mean()

(57.952379948397635, 61.523620051602364)

# Olasılığa giriş
## Olasılık Dağılımları: Olayların olabilirliğinin sayısal ifadesidir
## Rassal değişkenler ve olasılık dağılımları : Değerlerin bir deneyin sonuçlarından alan değişkene rassal değişken denir. örn: Yazı Tura, yazı veya tura gelebilir
## Dağılım, Evrende bazı olaylar gerçekleşiyor, bu olayların sayısal karşılıklarının ortaya çıkardığı yapıya dağılım denir
## Olasılık dağılımı: Bir rassal olaya ait değerler ve bu değerlerin gerçekleşme olasılıklarının bir arada ifade edilmesine denir.
## Olasılık fonksiyonu: Bir değişkenin herhangi bir değeri alması, olasılığını hesaplayan fonksiyon
--------------
## Dağılım - olayların sayısal karşılığı
## Olasılık Dağılımı Olayların sayısal karşışığının gerçekleşme olasılıklarıyla birlikte sunulması

------------------------

## Kesikli Olasılık dağılımları : Bernoulli, Binom, Poisson....
## Sürekli Olasılık dağılımları : Normal dağılım, Uniform dağılım, Üstel dağılım

## Beronoulli dağılımı
${\displaystyle f(k;p) = p^{k} (1-p)^{1-k}\quad {\text {for }} k \in \{0,1\} }$


$ { \displaystyle  \operatorname {E} [X] = p }$

$ {\displaystyle  \operatorname {Var} [X] = pq = p (1-p)}$


In [25]:
from scipy.stats import bernoulli

In [26]:
p = 0.6

In [32]:
rv = bernoulli(p)
rv.pmf(k = 0)

0.4

# Büyük Sayılar Yasası
## Bir rassal değişkenin uzun vadeli kararlılığını tanımlayan bir olasılık teorimidir.

In [45]:
import numpy as np
rng = np.random.RandomState(123)
for i in np.arange(1,21):
    deney_sayisi = 2**i
    yazi_turalar= rng.randint(0,2, size = deney_sayisi)
    yazi_olasiliklari = np.mean(yazi_turalar)
    print('Atış sayısı: ',deney_sayisi,"----", 'Yazı Olasılığı: %.2f' % (yazi_olasiliklari * 100))

Atış sayısı:  2 ---- Yazı Olasılığı: 50.00
Atış sayısı:  4 ---- Yazı Olasılığı: 0.00
Atış sayısı:  8 ---- Yazı Olasılığı: 62.50
Atış sayısı:  16 ---- Yazı Olasılığı: 43.75
Atış sayısı:  32 ---- Yazı Olasılığı: 46.88
Atış sayısı:  64 ---- Yazı Olasılığı: 56.25
Atış sayısı:  128 ---- Yazı Olasılığı: 50.78
Atış sayısı:  256 ---- Yazı Olasılığı: 52.73
Atış sayısı:  512 ---- Yazı Olasılığı: 52.93
Atış sayısı:  1024 ---- Yazı Olasılığı: 50.20
Atış sayısı:  2048 ---- Yazı Olasılığı: 48.58
Atış sayısı:  4096 ---- Yazı Olasılığı: 49.49
Atış sayısı:  8192 ---- Yazı Olasılığı: 49.58
Atış sayısı:  16384 ---- Yazı Olasılığı: 49.96
Atış sayısı:  32768 ---- Yazı Olasılığı: 50.00
Atış sayısı:  65536 ---- Yazı Olasılığı: 49.68
Atış sayısı:  131072 ---- Yazı Olasılığı: 49.97
Atış sayısı:  262144 ---- Yazı Olasılığı: 50.13
Atış sayısı:  524288 ---- Yazı Olasılığı: 50.01
Atış sayısı:  1048576 ---- Yazı Olasılığı: 50.09


In [43]:
rng.randint(0,2, size =  4)

array([1, 0, 0, 0])

# Binom Dağılımı  (Nominal, Kategorik,n kere deneme)
### Bağımsız n deneme sonucu k başarılı olma ile ilgilendiğinizde kullanılan dağılımdır.
### E(x)= n.p
## var(x)= np (1-p)
## f(x; n,p) = Kombinasyon(n,x) p^x (1-p)^(n-x), x = 0,1,2,......,n

## İş uygulaması: Reklam Harcaması Optimizasyonu
### Çeşitli Mecralara reklam veriliyor, reklamların tıklanma ve geri dönüşüm oranları optimize edilmeye çalışılıyor. Buna yönelik olarak belirli bir mecrada çeşitli senaryolara göre reklama tıklama olasılıkları hesaplanmak isteniliyor.
### Detaylar: Bir mecrada reklam verilecek, Dağılım ve reklama tıklama olasılığı biliniyor(0.01)
### Soru : Reklamı 100 kişi gördüğünde 1, 5 yada 10 tıklanma olasılığı nedir?

In [2]:
from scipy.stats import binom

In [5]:
p = 0.01
n=100
rv = binom(n,p)
print(rv.pmf(1))
print(rv.pmf(5))
print(rv.pmf(10))

0.36972963764972666
0.002897787123761478
7.006035693977194e-08


# Poisson dağılımı (rassal değişken, kesikli)
# Belirli bir zaman aralığında belirli bir alanda nadiren rastlanan olayların olasılıklarını hesaplamak için kullanılır.
## f(x,lamda) = lamda^x - e^(-x) ,  E(x)= lamda, var(x) = lamda
## bir olayın nadir olabilimesi için:    n>50 , n*p < 5 
## 10 bin kelimeden oluşan bir kitapta hatalı kelime sayısı
## 4000 öğrencili okulda not girişinin hatalı yapılması
## bir iş gününde çağrı merkezine gelen taktir sayısı.
## Kredi kartı işlemlerinde sahtekarlık olması.
## Rötara düşen uçak sayısı.

# Passion Uygulama: İlan giriş hata olasılıkları.
## Detaylar: Bir yıl süresince ölçümler yapılıyor, Dağılım biliniyor (Possion) ve Lambda 0.1(ortalama hatası), hiç hata olmaması
## Soru: 3 hata olması ve 5 hata olması olasılıkları nedir ?

In [8]:
from scipy.stats import poisson

In [12]:
lambda_=0.1

In [14]:
rv= poisson(mu= lambda_)
print(rv.pmf(k=0))
print(rv.pmf(k=3))
print(rv.pmf(k=5))

0.9048374180359595
0.00015080623633932676
7.54031181696634e-08


In [15]:
# İŞ uygulaması: Satışaolasılıklarının hesaplanması
##Problem : bir yatırım/toplantı öncesinde gelecek ay ile ilgili sayışların belirli değerlerde gerçekleşmesi olasılıkları belirlenmek isteniyor.
## Detaylar Dağılımın normal olduğu biliniyor, Aylık ortalama satış sayısı 80K, standart sapması 5K,
## sorular : 90k dan fazla satış yapma olasılığı nedir ? --- 

$$
f(x|\mu,\sigma^{2})=\frac{1}{\sqrt{2\pi\sigma^{2}}}e^{-\frac{(x-\mu)^{2}}{2\sigma^{2}}}
$$
### u = ortalama ya da dağılımın ebklenen değeri
### o = standart sapma
### o^2 = varyans

In [2]:
from scipy.stats import norm

In [8]:
## 90 dan fazla
1-norm.cdf(90,80,5)

0.02275013194817921

In [9]:
## 70 den fazla
1-norm.cdf(70,80,5)

0.9772498680518208

In [11]:
## 73 den fazla
norm.cdf(73,80,5)

0.08075665923377107

In [12]:
## 85 ile 90 arası olması 
norm.cdf(90,80,5)- norm.cdf(85,80,5)

0.13590512198327787

In [ ]:
### belirsilik altında karar vermeye çalışyoruz, bir şeyleri modellemeye veriye dökmeye çalışıyoruz, olasılık dağılımları olasılık değerleri veriyor. 
### uygun olasılık fonksiyonları ile olasılık hesapları yapıyoruz.